### ISSUE TITLE
Object layer processing

### ISSUE THREAD

**Issue by riklowe** [TomLinthwaite/SKTilemap#10]
Hi Tom

Currently you can only get objects by id, position, name or type.
Would be good to be able to iterate through the Objects in the object layer like this -

```
    let objectGroup = tileMap.getObjectGroup(name: "Object Layer 1")
    for object in objectGroup {
        //process object
    }
```

However, this produces the error as objectGroup does not conform to protocol SequenceType
Would be good if you get the object group to conform to sequence type protocol 
Note : this saves you from looping through the entire grid space looking for objects.

Thanks
Richard

**Comment by riklowe** [comment]
Note : I have found a way to do this but its not as clean

I added the following to SKTilemapObjectGroup

```
func getObjects() -> [SKTilemapObject] {

    var objects = [SKTilemapObject]()

    for object in self.objects {
        objects.append(object)
    }

    return objects
}
```

Then I can iterate with - 

```
    let objectGroup = tileMap.getObjectGroup(name: "Object Layer 1")

    for object in (objectGroup?.getObjects())! {

        object.printDebugDescription()

    }
```

**Comment by TomLinthwaite** [comment]
I've added a new function to the object group much like yours. Take a look at the new CHANGELOG.md file to see the update :)

**Comment by riklowe** [comment]
Great thanks
