### ISSUE TITLE
Support for OSX apps

### ISSUE THREAD

**Issue by DanieleBarone** [TomLinthwaite/SKTilemap#4]
Hello Tom,
 thank you for your great work

To use your library in a OSX app, I have modified your "SKTileMap" by adding  #if !os(OSX) ... #end in the "SKTilmapLayer.swift" for the following functions:

```
     #if !os(OSX)
    /* Returns a tile at a given touch position. A custom offset can also be used. */
    func tileAtTouchPosition(touch: UITouch, offset: CGPoint = CGPointZero) -> SKTilemapTile? {

        if let coord = coordAtTouchPosition(touch, offset: offset, round: true) {
            return tileAtCoord(coord)
        }

        return nil
    }
    #endif
```

AND:

```
    #if !os(OSX)
  func coordAtTouchPosition(touch: UITouch, offset: CGPoint = CGPointZero, round: Bool = true) -> CGPoint? {
        return coordAtPosition(touch.locationInNode(self), offset: offset, round: round)
    }
  #endif
```

Are you planning to make the library compatible to OSX apps as well?
Thank you for your consideration

**Comment by TomLinthwaite** [comment]
I guess in reality it should be compatible with OS X. The main reason I haven't done this is my own lack of knowledge with regards to the differences in each os. 

I'll add these changes tonIght and have a look at what else may need changing. If you have any ideas let e know :) or create a pull request and I'll implement yours.

**Comment by DanieleBarone** [comment]
Great thank you so much! I created a pull request! 
In terms of ideas, something to consider would be to use some of the mouse click events instead of touch events when targeting OSX (a similar consideration can be done for tvOS).
Thank you again for the fast reply!!!

```

  /**
   Handle screen click events.
   */

  override func mouseDown(theEvent: NSEvent) {

    let location = theEvent.locationInNode(self)
    ...

  }

  override func mouseDragged(theEvent: NSEvent) {

    let location = theEvent.locationInNode(self)
  ...
  }

  override func mouseUp(theEvent: NSEvent) {

    let location = theEvent.locationInNode(self)
    ...

  }

  override func mouseExited(theEvent: NSEvent) {

    let location = theEvent.locationInNode(self)
   ...

  }

```

**Comment by TomLinthwaite** [comment]
Hi Daniele I couldn't commit your pull request for some reason and I'm new to GitHub and couldn't work out why. Regardless I incorporated what you had so OSX is now supported.

I changed the project structure to show this, and you can compile the code by selecting the OSX target.

Some things are a bit weird though, for instance if you resize the window the camera bounds will not update to reflect it. I'm not sure how to fix it, probably have to update the bounds in `didChangeSize` function in the scene. Haven't got time right now though.

I'll continue to support OSX so once I have a chance to read up more about the differences I'll update it so it all works correctly. If you want to make another pull please do it from the latest version I think that's what mucked it up.

**Comment by DanieleBarone** [comment]
Great, thank you Tom! I am kind of new too, therefore no worries. 
Just to be sure, I deleted my repository and forked it again, so we may be luckier next time ;)
I will download the new version and play with it! Thank you again
