### ISSUE TITLE
Tile Map Loading Time

### ISSUE THREAD

**Issue by riklowe** [TomLinthwaite/SKTilemap#7]
Hi Tom

I noticed the loading time for a large map is slow using SKTileMap.
As a test I loaded the identical map in two apps, one using SKTileMap, the other JSTileMap (https://github.com/slycrel/JSTileMap)

The results can be seen below in the debug log outputs.

SKTileMap loading time for 50\* 500 Map (68 seconds)

08:38:09:817 -- GameScene.swift         -- didMoveToView
08:39:17:463 -- GameScene.swift         -- didMoveToView     -- SETUP FINISHED

JSTileMap loading time for 50 \* 500 Map (0.5 secs)

08:53:45:306 -- GameScene.swift         -- didMoveToView
2016-04-22 08:53:45.567 Swifty[1691:1096158] Layer Tile Layer 1 has zPosition -60.000000
2016-04-22 08:53:45.621 Swifty[1691:1096158] Layer Tile Layer 2 has zPosition -40.000000
08:53:45:788 -- GameScene.swift         -- didMoveToView     -- SETUP FINISHED

Happy to provide more information if required

Rgds
Richard

**Comment by TomLinthwaite** [comment]
It takes over a minute to load the map? Are you loading just the map or other stuff? I never had a wait like that. I'll run some tests when I get in from work. Thanks for the info

**Comment by riklowe** [comment]
No I am just loading the map. I have taken your code and just changed the map to a 50 \* 500 map.
Both timing test above were run on an IPAD 1 but I see similar differences when I run on Iphone 6 plus (see below)

Both are using the same map tmx

SKTileMap loading time for 50\* 500 Map (19 seconds)

11:17:32:339 -- GameScene.swift         -- didMoveToView    -- 34
11:17:32:345 -- SKTilemap.swift         -- loadTMX(name:)   -- 170
11:17:32:346 -- SKTilemapParser.swift   -- loadTilemap(filename:)   -- 30
11:17:32:355 -- SKTilemap.swift         -- init(filename:tmxParserAttributes:)  -- 141
11:17:32:357 -- SKTilemapTileset.swift  -- init(tmxParserAttributes:)   -- 60
11:17:32:358 -- SKTilemap.swift         -- add(tileset:)    -- 190
11:17:32:359 -- SKTilemapTileset.swift  -- addTileData(spriteSheet:)    -- 93
11:17:32:400 -- SKTilemapLayer.swift    -- init(tilemap:tmxParserAttributes:)   -- 59
11:17:32:401 -- SKTilemap.swift         -- add(tileLayer:zPosition:)    -- 230
11:17:32:401 -- SKTilemap.swift         -- alignLayer   -- 264
11:17:32:429 -- SKTilemapLayer.swift    -- initializeTilesWithData  -- 103
11:17:32:429 -- SKTilemapLayer.swift    -- removeAllTiles()     -- 142
11:17:41:851 -- SKTilemapLayer.swift    -- init(tilemap:tmxParserAttributes:)   -- 59
11:17:41:852 -- SKTilemap.swift         -- add(tileLayer:zPosition:)    -- 230
11:17:41:853 -- SKTilemap.swift         -- alignLayer   -- 264
11:17:41:880 -- SKTilemapLayer.swift    -- initializeTilesWithData  -- 103
11:17:41:880 -- SKTilemapLayer.swift    -- removeAllTiles()     -- 142
11:17:51:602 -- SKTilemapObjectGroup.swift  -- init(tilemap:tmxParserAttributes:)   -- 33
11:17:51:602 -- SKTilemap.swift         -- add(objectGroup:)    -- 337
11:17:51:614 -- SKTilemap.swift         -- enableTileClipping   -- 87
11:17:51:706 -- SKTilemap.swift         -- alignLayer   -- 264
11:17:51:707 -- SKTilemap.swift         -- alignLayer   -- 264
11:17:51:707 -- GameScene.swift         -- didMoveToView     -- SETUP FINISHED

JSTileMap loading time for 50 \* 500 Map (0.11 secs)

11:20:02:879 -- GameScene.swift         -- didMoveToView    -- 287
11:20:02:882 -- GameScene.swift         -- setupMap()   -- 377
2016-04-22 11:20:02.883 Swifty[352:34103] JSTileMap: mapNamed: map.tmx
2016-04-22 11:20:02.884 Swifty[352:34103] JSTileMap: mapNamed:withBaseZPosition:andZOrderModifier:, map.tmx
2016-04-22 11:20:02.885 Swifty[352:34103] JSTileMap: init
2016-04-22 11:20:02.889 Swifty[352:34103] TMXTilesetInfo: initWithGid:attributes:
2016-04-22 11:20:02.890 Swifty[352:34103] TMXTilesetInfo: setSourceImage:
2016-04-22 11:20:02.915 Swifty[352:34103] TMXLayerInfo: init
2016-04-22 11:20:02.916 Swifty[352:34103] TMXLayerInfo: init
2016-04-22 11:20:02.916 Swifty[352:34103] TMXObjectGroup: init
2016-04-22 11:20:02.918 Swifty[352:34103] TMXLayer: layerWithTilesetInfo:layerInfo:mapInfo:
2016-04-22 11:20:02.927 Swifty[352:34103] Layer Tile Layer 2 has zPosition -60.000000
2016-04-22 11:20:02.927 Swifty[352:34103] TMXLayer: layerWithTilesetInfo:layerInfo:mapInfo:
2016-04-22 11:20:02.966 Swifty[352:34103] Layer Tile Layer 1 has zPosition -40.000000
2016-04-22 11:20:02.967 Swifty[352:34103] JSTileMap: setCullNodes:
2016-04-22 11:20:02.967 Swifty[352:34103] JSTileMap: layerNamed:, Tile Layer 1
2016-04-22 11:20:02.967 Swifty[352:34103] JSTileMap: layerNamed:, Tile Layer 2
11:20:03:008 -- GameScene.swift         -- setupHUD()   -- 554
11:20:03:010 -- GameScene.swift         -- processLayers()  -- 982
11:20:03:329 -- GameScene.swift         -- addPlayer()  -- 838
11:20:03:330 -- GameScene.swift         -- processObjects()     -- 1344
2016-04-22 11:20:03.331 Swifty[352:34103] JSTileMap: groupNamed:, Object Layer 1
11:20:03:368 -- GameScene.swift         -- setupLevel()     -- 725
11:20:03:368 -- GameScene.swift         -- setupBackgroundMusic()   -- 526
11:20:03:560 -- GameScene.swift         -- prepareSoundEffects()    -- 453
11:20:03:627 -- GameScene.swift         -- setupBackground()    -- 425
11:20:03:628 -- GameScene.swift         -- startAnimation()     -- 413
11:20:03:642 -- GameScene.swift         -- startTimers()    -- 367
11:20:03:644 -- GameScene.swift         -- didMoveToView     -- SETUP FINISHED

**Comment by TomLinthwaite** [comment]
There's a 10 second gap in between it initialising one layer and not another. What's the difference between those layers? Or is it the object group? 

It doesn't seem possible for it to be with loading the layers since I don't get that sort of delay when I test with a map that size. 

Can you try removing a layer at a time (object group included) to try and find out exactly what's taking so long?

The only thing I can think of is it being the bloat it goes through validating everything as it sets a tile. RemoveAllTiles could be removed as well for.

**Comment by riklowe** [comment]
In the TMX i m using - 
Tile Layer 1 is the main map (couple of thousand filled tiles)
Tile Layer 2  has obstacles / boxes  (couple of 100 filled tiles)
Object Layer 1 is empty

The issue is not the Object layer (as can be seen in the log above) 
11:17:51:602 -- SKTilemap.swift -- add(objectGroup:) -- 337
this happens only 5 lines from the end.

To help track down the issue I have tried to log where the code is spending its time 
There are several routines in SKTilemapParser.swift and SKTilemapLayer.swift that are repeatedly being called.

However the time between Parser start and end is NOT significant
PARSER START - 14:41:10:447 -- SKTilemapParser.swift    -- loadTilemap(filename:)
PARSER END     - 14:41:10:522 -- SKTilemapLayer.swift   -- init(tilemap:tmxParserAttributes:)

So I would focus on the function in SKTilemapLayer.swift.

MORE DETAILED LOG
NOTE :  I have had to remove 10's of thousands of lines from the log so I could post. 

14:41:10:438 -- GameScene.swift         -- didMoveToView    -- 34
14:41:10:446 -- SKTilemap.swift         -- loadTMX(name:)   -- 170
14:41:10:447 -- SKTilemapParser.swift   -- loadTilemap(filename:)   -- 33
14:41:10:454 -- SKTilemapParser.swift   -- 

parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)    -- 58
14:41:10:456 -- SKTilemap.swift         -- init(filename:tmxParserAttributes:)  -- 141
14:41:10:458 -- SKTilemapParser.swift   -- parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)     -- 58
14:41:10:459 -- SKTilemapTileset.swift  -- init(tmxParserAttributes:)   -- 60
14:41:10:459 -- SKTilemap.swift         -- add(tileset:)    -- 190
14:41:10:461 -- SKTilemapParser.swift   -- parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)     -- 58
14:41:10:461 -- SKTilemapTileset.swift  -- addTileData(spriteSheet:)    -- 93
14:41:10:505 -- SKTilemapParser.swift   -- parser(_:didEndElement:namespaceURI:qualifiedName:)  -- 220
14:41:10:506 -- SKTilemapParser.swift   -- parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)     -- 58
14:41:10:506 -- SKTilemapParser.swift   -- parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)     -- 58
14:41:10:507 -- SKTilemapParser.swift   -- parser(_:didEndElement:namespaceURI:qualifiedName:)  -- 220
14:41:10:507 -- SKTilemapParser.swift   -- parser(_:didEndElement:namespaceURI:qualifiedName:)  -- 220
14:41:10:507 -- SKTilemapParser.swift   -- parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)     -- 58
14:41:10:508 -- SKTilemapParser.swift   -- parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)     -- 58
14:41:10:508 -- SKTilemapParser.swift   -- parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)     -- 58
14:41:10:509 -- SKTilemapParser.swift   -- parser(_:didEndElement:namespaceURI:qualifiedName:)  -- 220
14:41:10:510 -- SKTilemapParser.swift   -- parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)     -- 58
14:41:10:510 -- SKTilemapParser.swift   -- parser(_:didEndElement:namespaceURI:qualifiedName:)  -- 220
14:41:10:511 -- SKTilemapParser.swift   -- parser(_:didEndElement:namespaceURI:qualifiedName:)  -- 220
14:41:10:511 -- SKTilemapParser.swift   -- parser(_:didEndElement:namespaceURI:qualifiedName:)  -- 220
14:41:10:512 -- SKTilemapParser.swift   -- parser(_:didStartElement:namespaceURI:qualifiedName:attributes:)     -- 58
14:41:10:512 -- SKTilemapParser.swift   -- parser(_:didEndElement:namespaceURI:qualifiedName:)  -- 220
14:41:10:513 -- SKTilemapParser.swift   -- parser(_:didEndElement:namespaceURI:qualifiedName:)  -- 220
14:41:10:513 -- SKTilemapParser.swift   -- parser(_:didEndElement:namespaceURI:qualifiedName:)  -- 220

1000's of above entries removed from the log

14:41:10:522 -- SKTilemapLayer.swift    -- init(tilemap:tmxParserAttributes:)   -- 66
14:41:10:523 -- SKTilemap.swift         -- add(tileLayer:zPosition:)    -- 230
14:41:10:523 -- SKTilemap.swift         -- alignLayer   -- 264
14:41:10:551 -- SKTilemapLayer.swift    -- initializeTilesWithData  -- 110

14:41:10:551 -- SKTilemapLayer.swift    -- removeAllTiles()     -- 157
14:41:10:551 -- SKTilemapLayer.swift    -- removeTileAtCoord    -- 144
14:41:10:551 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:tile:)    -- 221
14:41:10:552 -- SKTilemapLayer.swift    -- isValidCoord(x:y:)   -- 133
14:41:10:552 -- SKTilemapLayer.swift    -- tileAtCoord  -- 169
14:41:10:552 -- SKTilemapLayer.swift    -- isValidCoord(x:y:)   -- 133

14:41:10:552 -- SKTilemapLayer.swift    -- removeTileAtCoord    -- 144
14:41:10:553 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:tile:)    -- 221
14:41:10:553 -- SKTilemapLayer.swift    -- isValidCoord(x:y:)   -- 133
14:41:10:553 -- SKTilemapLayer.swift    -- tileAtCoord  -- 169
14:41:10:553 -- SKTilemapLayer.swift    -- isValidCoord(x:y:)   -- 133

14:41:10:554 -- SKTilemapLayer.swift    -- removeTileAtCoord    -- 144
14:41:10:554 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:tile:)    -- 221
14:41:10:554 -- SKTilemapLayer.swift    -- isValidCoord(x:y:)   -- 133
14:41:10:554 -- SKTilemapLayer.swift    -- tileAtCoord  -- 169
14:41:10:555 -- SKTilemapLayer.swift    -- isValidCoord(x:y:)   -- 133

14:41:10:555 -- SKTilemapLayer.swift    -- removeTileAtCoord    -- 144
14:41:10:555 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:tile:)    -- 221
14:41:10:555 -- SKTilemapLayer.swift    -- isValidCoord(x:y:)   -- 133
14:41:10:556 -- SKTilemapLayer.swift    -- tileAtCoord  -- 169
14:41:10:556 -- SKTilemapLayer.swift    -- isValidCoord(x:y:)   -- 133

14:41:10:556 -- SKTilemapLayer.swift    -- removeTileAtCoord    -- 144
14:41:10:556 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:tile:)    -- 221
14:41:10:556 -- SKTilemapLayer.swift    -- isValidCoord(x:y:)   -- 133
14:41:10:557 -- SKTilemapLayer.swift    -- tileAtCoord  -- 169
14:41:10:557 -- SKTilemapLayer.swift    -- isValidCoord(x:y:)   -- 133

14:41:10:557 -- SKTilemapLayer.swift    -- removeTileAtCoord    -- 144
14:41:10:557 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:tile:)    -- 221
14:41:10:558 -- SKTilemapLayer.swift    -- tileAtCoord  -- 169

14:41:10:558 -- SKTilemapLayer.swift    -- removeTileAtCoord    -- 144
14:41:10:558 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:tile:)    -- 221
14:41:10:558 -- SKTilemapLayer.swift    -- tileAtCoord  -- 169

14:41:10:559 -- SKTilemapLayer.swift    -- removeTileAtCoord    -- 144
14:41:10:559 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:tile:)    -- 221
14:41:10:559 -- SKTilemapLayer.swift    -- tileAtCoord  -- 169

14:41:10:559 -- SKTilemapLayer.swift    -- removeTileAtCoord    -- 144
14:41:10:560 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:tile:)    -- 221
14:41:10:560 -- SKTilemapLayer.swift    -- tileAtCoord  -- 169

14:41:10:560 -- SKTilemapLayer.swift    -- removeTileAtCoord    -- 144
14:41:10:560 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:tile:)    -- 221
14:41:10:561 -- SKTilemapLayer.swift    -- tileAtCoord  -- 169

1000's of above entries removed from the log

14:41:10:618 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:id:)  -- 258
14:41:10:619 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:id:)  -- 258
14:41:10:619 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:id:)  -- 258
14:41:10:620 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:id:)  -- 258
14:41:10:621 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:id:)  -- 258
14:41:10:621 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:id:)  -- 258
14:41:10:622 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:id:)  -- 258
14:41:10:623 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:id:)  -- 258
14:41:10:624 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:id:)  -- 258
14:41:10:624 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:id:)  -- 258

1000's of above entries removed from the log

14:41:18:006 -- SKTilemapLayer.swift    -- tilePositionAtCoord(_:_:offset:)     -- 279
14:41:18:007 -- SKTilemapLayer.swift    -- tilePositionAtCoord(_:_:offset:)     -- 279
14:41:18:007 -- SKTilemapLayer.swift    -- tilePositionAtCoord(_:_:offset:)     -- 279
14:41:18:085 -- SKTilemapLayer.swift    -- tilePositionAtCoord(_:_:offset:)     -- 279
14:41:18:086 -- SKTilemapLayer.swift    -- tilePositionAtCoord(_:_:offset:)     -- 279
14:41:18:086 -- SKTilemapLayer.swift    -- tilePositionAtCoord(_:_:offset:)     -- 279
14:41:18:194 -- SKTilemapLayer.swift    -- tilePositionAtCoord(_:_:offset:)     -- 279
14:41:18:197 -- SKTilemapLayer.swift    -- tilePositionAtCoord(_:_:offset:)     -- 279
14:41:18:197 -- SKTilemapLayer.swift    -- tilePositionAtCoord(_:_:offset:)     -- 279
14:41:18:198 -- SKTilemapLayer.swift    -- tilePositionAtCoord(_:_:offset:)     -- 279

1000's of above entries removed from the log

14:41:19:709 -- SKTilemapLayer.swift    -- init(tilemap:tmxParserAttributes:)   -- 66
14:41:19:709 -- SKTilemap.swift         -- add(tileLayer:zPosition:)    -- 230
14:41:19:710 -- SKTilemap.swift         -- alignLayer   -- 264
14:41:19:737 -- SKTilemapLayer.swift    -- initializeTilesWithData  -- 110

14:41:19:738 -- SKTilemapLayer.swift    -- removeAllTiles()     -- 157
14:41:19:738 -- SKTilemapLayer.swift    -- removeTileAtCoord    -- 144
14:41:19:739 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:tile:)    -- 221
14:41:19:739 -- SKTilemapLayer.swift    -- isValidCoord(x:y:)   -- 133
14:41:19:740 -- SKTilemapLayer.swift    -- tileAtCoord  -- 169
14:41:19:740 -- SKTilemapLayer.swift    -- isValidCoord(x:y:)   -- 133

14:41:19:741 -- SKTilemapLayer.swift    -- removeTileAtCoord    -- 144
14:41:19:741 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:tile:)    -- 221
14:41:19:742 -- SKTilemapLayer.swift    -- isValidCoord(x:y:)   -- 133
14:41:19:742 -- SKTilemapLayer.swift    -- tileAtCoord  -- 169
14:41:19:743 -- SKTilemapLayer.swift    -- isValidCoord(x:y:)   -- 133

14:41:19:743 -- SKTilemapLayer.swift    -- removeTileAtCoord    -- 144
14:41:19:743 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:tile:)    -- 221
14:41:19:744 -- SKTilemapLayer.swift    -- isValidCoord(x:y:)   -- 133
14:41:19:744 -- SKTilemapLayer.swift    -- tileAtCoord  -- 169
14:41:19:745 -- SKTilemapLayer.swift    -- isValidCoord(x:y:)   -- 133

14:41:19:745 -- SKTilemapLayer.swift    -- removeTileAtCoord    -- 144
14:41:19:745 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:tile:)    -- 221
14:41:19:746 -- SKTilemapLayer.swift    -- isValidCoord(x:y:)   -- 133
14:41:19:746 -- SKTilemapLayer.swift    -- tileAtCoord  -- 169
14:41:19:747 -- SKTilemapLayer.swift    -- isValidCoord(x:y:)   -- 133

14:41:19:747 -- SKTilemapLayer.swift    -- removeTileAtCoord    -- 144
14:41:19:747 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:tile:)    -- 221
14:41:19:748 -- SKTilemapLayer.swift    -- isValidCoord(x:y:)   -- 133
14:41:19:748 -- SKTilemapLayer.swift    -- tileAtCoord  -- 169
14:41:19:749 -- SKTilemapLayer.swift    -- isValidCoord(x:y:)   -- 133

14:41:19:749 -- SKTilemapLayer.swift    -- removeTileAtCoord    -- 144
14:41:19:749 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:tile:)    -- 221
14:41:19:750 -- SKTilemapLayer.swift    -- tileAtCoord  -- 169

14:41:19:751 -- SKTilemapLayer.swift    -- removeTileAtCoord    -- 144
14:41:19:751 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:tile:)    -- 221
14:41:19:751 -- SKTilemapLayer.swift    -- tileAtCoord  -- 169

14:41:19:752 -- SKTilemapLayer.swift    -- removeTileAtCoord    -- 144
14:41:19:752 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:tile:)    -- 221
14:41:19:753 -- SKTilemapLayer.swift    -- tileAtCoord  -- 169

14:41:19:753 -- SKTilemapLayer.swift    -- removeTileAtCoord    -- 144
14:41:19:754 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:tile:)    -- 221
14:41:19:754 -- SKTilemapLayer.swift    -- tileAtCoord  -- 169

14:41:19:754 -- SKTilemapLayer.swift    -- removeTileAtCoord    -- 144
14:41:19:755 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:tile:)    -- 221
14:41:19:755 -- SKTilemapLayer.swift    -- tileAtCoord  -- 169

1000's of above entries removed from the log

14:41:19:812 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:id:)  -- 258
14:41:19:813 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:id:)  -- 258
14:41:19:814 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:id:)  -- 258
14:41:19:815 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:id:)  -- 258
14:41:19:815 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:id:)  -- 258
14:41:19:816 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:id:)  -- 258
14:41:19:817 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:id:)  -- 258
14:41:19:818 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:id:)  -- 258
14:41:19:819 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:id:)  -- 258
14:41:19:820 -- SKTilemapLayer.swift    -- setTileAtCoord(_:_:id:)  -- 258

1000's of above entries removed from the log

14:41:22:609 -- SKTilemapLayer.swift    -- tilePositionAtCoord(_:_:offset:)     -- 279
14:41:22:610 -- SKTilemapLayer.swift    -- tilePositionAtCoord(_:_:offset:)     -- 279
14:41:22:610 -- SKTilemapLayer.swift    -- tilePositionAtCoord(_:_:offset:)     -- 279
14:41:22:611 -- SKTilemapLayer.swift    -- tilePositionAtCoord(_:_:offset:)     -- 279
14:41:23:184 -- SKTilemapLayer.swift    -- tilePositionAtCoord(_:_:offset:)     -- 279
14:41:23:185 -- SKTilemapLayer.swift    -- tilePositionAtCoord(_:_:offset:)     -- 279
14:41:23:185 -- SKTilemapLayer.swift    -- tilePositionAtCoord(_:_:offset:)     -- 279
14:41:23:186 -- SKTilemapLayer.swift    -- tilePositionAtCoord(_:_:offset:)     -- 279
14:41:23:373 -- SKTilemapLayer.swift    -- tilePositionAtCoord(_:_:offset:)     -- 279
14:41:23:374 -- SKTilemapLayer.swift    -- tilePositionAtCoord(_:_:offset:)     -- 279

1000's of above entries removed from the log

14:41:29:209 -- SKTilemapObjectGroup.swift  -- init(tilemap:tmxParserAttributes:)   -- 33
14:41:29:209 -- SKTilemap.swift         -- add(objectGroup:)    -- 337
14:41:29:221 -- SKTilemap.swift         -- enableTileClipping   -- 87
14:41:29:311 -- SKTilemap.swift         -- alignLayer   -- 264
14:41:29:312 -- SKTilemap.swift         -- alignLayer   -- 264
14:41:29:312 -- GameScene.swift         -- didMoveToView     -- SETUP FINISHED

Hope this helps

Rgds
Richard

**Comment by TomLinthwaite** [comment]
I've tried to get the same results but don't experience nothing like the delay you get when loading a map. 
Im just loading the basic 50x500 map I have in the project though. 
On iPhone 5S I get 2.2 seconds
On iPhone 6S I get 1.2 seconds
And on the simulator its about 0.6 to 0.8 seconds to load the map.

I also tried to remove the extra bloat when a layer is created and just adding the tile directly to the array without doing any error checking and not calling removeAllTiles etc... And got near enough the same results.

Please don't forget your map is huge (25000 tiles) for one layer. Having another layer effectively doubles this. Even though there are no tiles in some spaces, loops like "removeAllTiles" will still loop through every coordinate (so in your case 50000 times for both layers). Note that removeAllTiles is the only function where I actually do this (excluding the initialise which should only be called once really).

Do you mind me asking why your map needs to be this big? I'm just curious. I'm imagining a shoot'em up or jumping game :P

**Comment by riklowe** [comment]
Strange that you are getting good load times. Yes its a platformer and 500 makes a good length for each level.

**Comment by riklowe** [comment]
I could send you the tax file I am using if that would help ?

**Comment by riklowe** [comment]
tmx file !

**Comment by TomLinthwaite** [comment]
Yea if you don't mind, I would like to try and solve this. Just a thought thought though. Since you're targeting iOS that map is huge and there is probably a better way to do it. You have a lot of nodes in memory. Even more when you add objects/player/particle effects/UI and what ever else. Not trying to tell you how to go about your project. Just saying it might be worth thinking about a different approach.

**Comment by riklowe** [comment]
do you have an email address I can send the file to ?

**Comment by TomLinthwaite** [comment]
Oh yea forgot about that sorry. Tomlinthwaite at iCloud . Com

**Comment by riklowe** [comment]
OK - have sent project and map file via email.

Regards your other comments - Up to now I have been using JSTileMap - and can load the file and apply all of my physics and other objects in about 0.8 of a second. Regards memory usage - its currently at 24.MB - with all assets loaded - and runs at 60 fps - so its just not been an issue.

However - I would love to be using a full Swift version rather than a mix of Swift and Object C - which is why I am interested in your project.

**Comment by TomLinthwaite** [comment]
Right I've fixed the issue. Try downloading the latest build and trying it out. Literally been thinking about this all day and wondering what it could be. Turns out it was the waste of time calls to try and create a tile when the GID is zero. Skip all those tiles and it loads fast. Just let me know its working ok for you before I close this :P

**Comment by TomLinthwaite** [comment]
Oh yea and your map is 500x50 not 50x500 lol which i why I was wondering what type of game it is :)

**Comment by riklowe** [comment]
Hi Tom - yes that seemed to have solved the issue.
Running on Iphone 6 plus I get the following -

21:01:47:684 -- GameScene.swift         -- didMoveToView    -- 35
21:01:48:637 -- GameScene.swift         -- didMoveToView     -- SETUP FINISHED

Great job. Thanks

**Comment by TomLinthwaite** [comment]
Great, I think thats acceptable for a map that size. I still may look into only adding children within a certain area of the map so even maps 100x that size can be supported. It's not something I want to work on now though. I want to continue adding basic Tiled features. Thanks for your feedback it means a lot. I'm glad I can get these things sorted out without having to find them myself.
